"use client";

import "./terms-of-service.css";
import Footer from "../../components/Footer";
import {
  SUPPORT_EMAIL,
  SUPPORT_PHONE_DISPLAY,
} from "../../../lib/siteContact";

export default function TermsOfServicePage() {
  return (
    <div className="terms-page">
      <section className="terms-hero">
        <div className="terms-overlay">
          <h1>Terms of Service</h1>
          <p>Terms and conditions for access and use of UTSAVAS</p>
        </div>
      </section>

      <section className="terms-content">
        <div className="terms-card">
          <h2>Terms &amp; Conditions of UTSAVAS</h2>

          <p>
            This document is an electronic record in terms of the Information
            Technology Act, 2000 and the applicable rules thereunder, including
            amendments from time to time. This electronic record is generated by
            a computer system and does not require any physical or digital
            signatures.
          </p>

          <p>
            This document is published in accordance with Rule 3(1) of the
            Information Technology (Intermediaries Guidelines and Digital Media
            Ethics Code) Rules, 2021, which requires publishing the rules and
            regulations, privacy policy, and terms and conditions for access or
            usage of the UTSAVAS website and app.
          </p>

          <p className="terms-alert">
            Please read these terms and conditions carefully before using the
            website or app. Accessing, browsing, or otherwise using UTSAVAS
            implies your agreement to be bound by these terms and conditions.
          </p>

          <h3>1. Acknowledgment and acceptance of Terms of Service</h3>
          <p>
            UTSAVAS owns and operates its website, app, and related services.
            These services are provided to you subject to these Terms of
            Service, along with any operating rules, policies, or guidelines
            that may be published by UTSAVAS from time to time.
          </p>
          <p>
            These Terms of Service constitute the entire agreement between you
            and UTSAVAS regarding access to and use of the platform. By
            registering, browsing, or using the website/app, you agree to be
            bound by these terms.
          </p>

          <h3>2. Services void where prohibited</h3>
          <p>
            Use of the services is void where prohibited by law. By using
            UTSAVAS, you represent and warrant that you have the right,
            authority, and capacity to enter into this agreement and comply with
            these terms.
          </p>

          <h3>3. Registration</h3>
          <p>
            You may be required to register with UTSAVAS to discover,
            shortlist, enquire about, review, or book venues listed on the
            platform. To register, you may need to provide valid contact
            information such as your mobile number or email address and create a
            password.
          </p>
          <p>
            By registering, you confirm that the information provided by you is
            accurate and current. You also consent to receive service-related
            and promotional communications through email, calls, SMS, or
            WhatsApp, subject to applicable law. It is your responsibility to
            provide correct information, and UTSAVAS shall not be responsible
            for issues arising from inaccurate details.
          </p>
          <p>
            UTSAVAS reserves the right to decline new registrations, cancel
            accounts, or suspend access at any time in the event of misuse,
            suspicious activity, breach of these terms, or legal necessity.
          </p>

          <h3>4. Medium of communication</h3>
          <p>
            UTSAVAS may send administrative, service-related, and promotional
            communications through email, calls, SMS, WhatsApp, or other
            reasonable channels. You may opt out of promotional communications
            where such option is made available.
          </p>

          <h3>5. Description of service</h3>
          <p>
            UTSAVAS is a venue discovery and booking platform that helps users
            explore wedding halls, banquet halls, party venues, resorts, farm
            houses, lawns, convention halls, and related event spaces.
          </p>
          <p>
            UTSAVAS acts as an intermediary platform where venue owners,
            vendors, and service providers may list their properties or
            services. UTSAVAS does not independently guarantee the accuracy,
            completeness, authenticity, pricing, availability, or quality of
            any listing, statement, or service provided by third-party vendors.
            Users are responsible for independently verifying details before
            finalizing any booking or transaction.
          </p>

          <h3>6. Limitation of liability</h3>
          <p>
            You acknowledge that UTSAVAS functions as an intermediary platform.
            To the fullest extent permitted by law, UTSAVAS shall not be liable
            for any direct, indirect, incidental, consequential, special, or
            exemplary damages arising from your use of the platform, inability
            to use the platform, dealings with third-party vendors, service
            failures, cancellations, disputes, personal injury, loss of data, or
            financial losses.
          </p>
          <p>
            Any engagement, booking, or transaction you enter into with a venue
            owner or service provider listed on UTSAVAS is solely between you
            and that third party. UTSAVAS shall not be liable for the acts,
            omissions, promises, conduct, goods, or services of any such third
            party.
          </p>

          <h3>7. Content</h3>
          <p>
            You are solely responsible for any content, data, reviews, images,
            messages, or other materials submitted, posted, or shared by you on
            UTSAVAS. By posting content, you grant UTSAVAS a non-exclusive,
            worldwide, royalty-free license to use, reproduce, display, modify,
            distribute, and publish such content for platform operations,
            marketing, and service improvement.
          </p>
          <p>
            UTSAVAS does not guarantee the accuracy, quality, or legality of
            content posted by users or third parties and shall not be liable for
            any such content.
          </p>

          <h3>8. Grievance cell</h3>
          <p>
            If you come across any violation, misuse, objectionable content, or
            unlawful activity on the platform, you may contact us in writing at:
          </p>
          <div className="terms-contact">
            <p>
              <strong>Email:</strong> {SUPPORT_EMAIL}
            </p>
            <p>
              <strong>Support number:</strong> {SUPPORT_PHONE_DISPLAY}
            </p>
            <p>
              <strong>Address:</strong> 285/A, 14th Main Rd, Siddanna Layout,
              Banashankari Stage II, Banashankari, Bengaluru, Karnataka 560070
            </p>
          </div>

          <h3>9. Copyright policy / infringing material</h3>
          <p>
            You may not post, distribute, or reproduce any copyrighted
            material, trademark, or proprietary information without proper
            authorization. If you believe your intellectual property rights have
            been infringed through content on UTSAVAS, please contact us with
            the relevant details and supporting information.
          </p>

          <h3>10. Customer care</h3>
          <p>
            For questions, complaints, or service-related concerns, you may
            contact UTSAVAS using the details provided above.
          </p>

          <h3>11. No spamming</h3>
          <p>
            You must not use the UTSAVAS platform for chain letters, junk mail,
            spam, unsolicited marketing, bulk messaging, or similar prohibited
            communication practices. UTSAVAS may suspend or terminate access for
            such misuse.
          </p>

          <h3>12. Notices</h3>
          <p>
            UTSAVAS may provide notices through email, website postings, app
            notifications, or other reasonable means. Such communication shall
            constitute adequate notice to users.
          </p>

          <h3>13. Privacy policy</h3>
          <p>
            UTSAVAS respects the privacy of its users. Collection, use,
            processing, storage, and sharing of personal data are governed by
            the UTSAVAS Privacy Policy. By using the platform, you consent to
            such collection and processing in accordance with applicable laws.
          </p>

          <h3>14. Security</h3>
          <p>
            You are responsible for maintaining the confidentiality of your
            account credentials and for all activity under your account. You
            agree to notify UTSAVAS immediately of any unauthorized access or
            security breach involving your account.
          </p>

          <h3>15. No commercial misuse of the service</h3>
          <p>
            Your right to use UTSAVAS is personal and non-transferable. You may
            not exploit, reproduce, resell, automate, scrape, or commercially
            misuse the platform without prior written consent from UTSAVAS.
          </p>

          <h3>16. User conduct</h3>
          <p>
            You agree not to use UTSAVAS for any unlawful, fraudulent,
            misleading, abusive, defamatory, obscene, harmful, infringing, or
            otherwise objectionable activity. You also agree not to upload
            viruses, attempt unauthorized access, harvest user data, impersonate
            others, or interfere with the proper functioning of the platform.
          </p>

          <h3>17. Indemnification</h3>
          <p>
            You agree to indemnify and hold harmless UTSAVAS, its owners,
            affiliates, employees, agents, and partners from any claims,
            liabilities, losses, damages, or expenses arising out of your use of
            the platform, your content, your violation of these terms, or your
            violation of any rights of a third party.
          </p>

          <h3>18. Termination</h3>
          <p>
            You may stop using UTSAVAS at any time. UTSAVAS may suspend,
            restrict, or terminate your access immediately and without prior
            notice if you violate these terms or if such action is necessary to
            protect the platform, users, or comply with law.
          </p>

          <h3>19. Transactions with third parties</h3>
          <p>
            UTSAVAS is not responsible for your dealings with venue owners,
            merchants, vendors, or other third parties found through the
            platform. All bookings, payments, cancellations, warranties, and
            disputes are solely between you and the applicable third party,
            unless expressly stated otherwise.
          </p>

          <h3>20. Links to third-party sites</h3>
          <p>
            Links to third-party websites may be provided for convenience.
            UTSAVAS does not control and is not responsible for the content,
            products, services, policies, or practices of such linked sites.
          </p>

          <h3>21. Violation of terms by other users</h3>
          <p>
            If you believe another user or listing violates these terms, you may
            report the issue to UTSAVAS through our contact details or support
            channels.
          </p>

          <h3>22. Disclaimer of warranties</h3>
          <p>
            UTSAVAS is provided on an &quot;as is&quot; and &quot;as available&quot; basis.
            UTSAVAS disclaims all warranties, express or implied, including but
            not limited to merchantability, fitness for a particular purpose,
            non-infringement, uninterrupted availability, accuracy, and
            reliability of listings or services.
          </p>

          <h3>23. Modifications to the service and terms</h3>
          <p>
            UTSAVAS reserves the right to modify, suspend, or discontinue any
            part of the service at any time. We may also update these Terms of
            Service from time to time. Continued use of the platform after such
            updates constitutes acceptance of the revised terms.
          </p>

          <h3>24. Governing law</h3>
          <p>
            These Terms of Service shall be governed by and construed in
            accordance with the laws of India.
          </p>

          <h3>25. Dispute resolution</h3>
          <p>
            Any dispute, claim, or controversy arising out of or relating to
            these terms or the use of UTSAVAS shall be resolved through
            arbitration in accordance with the Arbitration and Conciliation Act,
            1996, as amended from time to time. The seat and venue of
            arbitration shall be Bengaluru, and the language of proceedings
            shall be English, unless otherwise required by law.
          </p>

          <h3>26. Jurisdiction</h3>
          <p>
            Subject to applicable arbitration provisions, the courts of
            Bengaluru, Karnataka shall have jurisdiction over matters arising
            from these terms.
          </p>

          <p className="terms-updated">
            Terms &amp; Conditions last updated on March 12, 2026.
          </p>
        </div>
      </section>

      <Footer />
    </div>
  );
}
