export const karnatakaDistricts = [
  "Bengaluru Urban",
  "Bengaluru Rural",
  "Mysuru",
  "Mandya",
  "Tumakuru",
  "Hassan",
  "Shivamogga",
  "Chitradurga",
  "Davanagere",
  "Ballari",
  "Koppal",
  "Raichur",
  "Kalaburagi",
  "Bidar",
  "Yadgir",
  "Vijayapura",
  "Bagalkote",
  "Belagavi",
  "Dharwad",
  "Gadag",
  "Haveri",
  "Uttara Kannada",
  "Dakshina Kannada",
  "Udupi",
  "Kodagu",
  "Chamarajanagar",
  "Kolar",
  "Chikkaballapura",
  "Ramanagara",
  "Chikkamagaluru"
];
