export const karnatakaSearchCities = [
  {
    label: "Bagalkote",
    value: "Bagalkote",
    locations: ["Bagalkote", "Badami", "Bilgi", "Hunagunda", "Jamkhandi", "Mudhol"],
  },
  {
    label: "Ballari",
    value: "Ballari",
    locations: ["Ballari", "Hadagali", "Hagaribommanahalli", "Kampli", "Kudligi", "Sandur", "Siruguppa"],
  },
  {
    label: "Belagavi",
    value: "Belagavi",
    locations: ["Belagavi", "Athani", "Bailhongal", "Gokak", "Hukkeri", "Khanapur", "Nippani", "Raibag", "Ramdurg", "Savadatti"],
  },
  {
    label: "Bengaluru",
    value: "Bengaluru",
    locations: [
      "Bannerghatta Road",
      "Basavanagudi",
      "Bengaluru East",
      "Bengaluru North",
      "Bengaluru South",
      "Bommanahalli",
      "Brookefield",
      "BTM Layout",
      "Devanahalli",
      "Doddaballapur",
      "Domlur",
      "Electronic City",
      "Frazer Town",
      "Hebbal",
      "Hennur",
      "Hoskote",
      "Indiranagar",
      "Jakkur",
      "Jayanagar",
      "JP Nagar",
      "Kengeri",
      "Koramangala",
      "KR Puram",
      "Mahadevapura",
      "Malleswaram",
      "Marathahalli",
      "Nelamangala",
      "Peenya",
      "Rajajinagar",
      "RT Nagar",
      "Sarjapur Road",
      "Thanisandra",
      "Ulsoor",
      "Varthur",
      "Whitefield",
      "Yelahanka",
      "Yeshwanthpur",
    ],
  },
  {
    label: "Bidar",
    value: "Bidar",
    locations: ["Bidar", "Aurad", "Basavakalyan", "Bhalki", "Humnabad", "Kamalnagar"],
  },
  {
    label: "Chamarajanagar",
    value: "Chamarajanagar",
    locations: ["Chamarajanagar", "Gundlupet", "Hanur", "Kollegal", "Yelandur"],
  },
  {
    label: "Chikkaballapura",
    value: "Chikkaballapura",
    locations: ["Bagepalli", "Chikkaballapura", "Chintamani", "Gauribidanur", "Gudibanda", "Sidlaghatta"],
  },
  {
    label: "Chikkamagaluru",
    value: "Chikkamagaluru",
    locations: ["Chikkamagaluru", "Kadur", "Koppa", "Mudigere", "Sringeri", "Tarikere"],
  },
  {
    label: "Chitradurga",
    value: "Chitradurga",
    locations: ["Challakere", "Chitradurga", "Hiriyur", "Holalkere", "Hosadurga", "Molakalmuru"],
  },
  {
    label: "Mangaluru",
    value: "Mangaluru",
    locations: ["Mangaluru", "Bantwal", "Belthangady", "Kadaba", "Puttur", "Sullia"],
  },
  {
    label: "Davanagere",
    value: "Davanagere",
    locations: ["Davanagere", "Channagiri", "Harihar", "Honnali", "Jagalur", "Nyamati"],
  },
  {
    label: "Dharwad",
    value: "Dharwad",
    locations: ["Dharwad", "Hubballi", "Alnavar", "Annigeri", "Kalghatgi", "Kundgol"],
  },
  {
    label: "Gadag",
    value: "Gadag",
    locations: ["Gadag", "Gajendragad", "Lakshmeshwar", "Mundargi", "Nargund", "Shirhatti"],
  },
  {
    label: "Hassan",
    value: "Hassan",
    locations: ["Hassan", "Alur", "Arakalagudu", "Arsikere", "Belur", "Channarayapatna", "Holenarasipura", "Sakleshpur"],
  },
  {
    label: "Haveri",
    value: "Haveri",
    locations: ["Haveri", "Byadagi", "Hangal", "Hirekerur", "Ranebennur", "Savanur", "Shiggaon"],
  },
  {
    label: "Kalaburagi",
    value: "Kalaburagi",
    locations: ["Kalaburagi", "Afzalpur", "Aland", "Chincholi", "Chitapur", "Jewargi", "Kalagi", "Sedam"],
  },
  {
    label: "Madikeri",
    value: "Madikeri",
    locations: ["Madikeri", "Somwarpet", "Virajpet", "Kodagu"],
  },
  {
    label: "Kolar",
    value: "Kolar",
    locations: ["Kolar", "Bangarapet", "KGF", "Malur", "Mulbagal"],
  },
  {
    label: "Koppal",
    value: "Koppal",
    locations: ["Koppal", "Gangavathi", "Kanakagiri", "Karatagi", "Kushtagi", "Yelburga"],
  },
  {
    label: "Mandya",
    value: "Mandya",
    locations: ["Mandya", "KR Pet", "Maddur", "Malavalli", "Nagamangala", "Pandavapura", "Srirangapatna"],
  },
  {
    label: "Mysuru",
    value: "Mysuru",
    locations: ["Mysuru", "HD Kote", "Hunsur", "KR Nagar", "Nanjangud", "Periyapatna", "T Narasipura"],
  },
  {
    label: "Raichur",
    value: "Raichur",
    locations: ["Raichur", "Devadurga", "Lingasugur", "Manvi", "Sindhanur", "Sirwar"],
  },
  {
    label: "Ramanagara",
    value: "Ramanagara",
    locations: ["Ramanagara", "Channapatna", "Harohalli", "Kanakapura", "Magadi"],
  },
  {
    label: "Shivamogga",
    value: "Shivamogga",
    locations: ["Shivamogga", "Bhadravati", "Hosanagara", "Sagara", "Shikaripura", "Soraba", "Thirthahalli"],
  },
  {
    label: "Tumakuru",
    value: "Tumakuru",
    locations: ["Tumakuru", "Chikkanayakanahalli", "Gubbi", "Kunigal", "Koratagere", "Madhugiri", "Pavagada", "Sira", "Tiptur", "Turuvekere"],
  },
  {
    label: "Udupi",
    value: "Udupi",
    locations: ["Udupi", "Brahmavara", "Byndoor", "Hebri", "Kapu", "Karkala", "Kundapura"],
  },
  {
    label: "Karwar",
    value: "Karwar",
    locations: ["Karwar", "Ankola", "Bhatkal", "Dandeli", "Haliyal", "Honnavar", "Joida", "Kumta", "Mundgod", "Siddapur", "Sirsi", "Yellapur"],
  },
  {
    label: "Vijayapura",
    value: "Vijayapura",
    locations: ["Vijayapura", "Basavana Bagewadi", "Devara Hipparagi", "Indi", "Kolhar", "Muddebihal", "Nidagundi", "Sindagi", "Talikoti"],
  },
  {
    label: "Hosapete",
    value: "Hosapete",
    locations: ["Hosapete", "Harapanahalli", "Kotturu"],
  },
  {
    label: "Yadgir",
    value: "Yadgir",
    locations: ["Yadgir", "Gurmitkal", "Shahapur", "Shorapur", "Wadgera"],
  },
];
